/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle6;

public class Library {
    public boolean someLibraryMethod() {
    	
    	System.out.println(new Integer("12").intValue());
    	System.out.println(new Double("12.3").doubleValue());
    	System.out.println(Integer.parseInt("101", 2));  // 5
    	
        return true;
    }
    
    public static void main(String args[]) {
    	Library l = new Library();
    	l.someLibraryMethod();
    }
}
